name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v5.0.4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles ('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v5.0.4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles ('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Upload Test report
        uses: actions/upload-artifact@v7.0.0
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v5.0.4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles ('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build Website
        id: build-website
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist-files
      - name: Output Contents
        run: ls
      - name: Deploy
        run: echo "Deploying......."
